/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  output: 'standalone',

  // SEO: Force trailing slash sur toutes les URLs (y compris homepage)
  trailingSlash: true,
  
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  
  experimental: {
    serverComponentsExternalPackages: []
  },

  compress: true,
  
  images: {
    unoptimized: true,
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'randomuser.me',
        pathname: '/**',
      }
    ],
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
  },

  // Redirections 404 - Nettoyage Montpellier
  async redirects() {
    return [
      // SATELLITES : Articles sans -montpellier → avec -montpellier
      { source: '/blog/satellites/conteneur-demenagement-international', destination: '/blog/satellites/conteneur-demenagement-international-montpellier', permanent: true },
      { source: '/blog/satellites/astuces-reduire-cout-demenagement', destination: '/blog/satellites/astuces-reduire-cout-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/aide-amis-demenagement', destination: '/blog/satellites/aide-amis-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/cout-demenagement-t3-2025', destination: '/blog/satellites/cout-demenagement-t3-2025-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-outre-mer-dom-tom', destination: '/blog/satellites/demenagement-outre-mer-dom-tom-montpellier', permanent: true },
      { source: '/blog/satellites/assurance-demenagement-piano', destination: '/blog/satellites/assurance-demenagement-piano-montpellier', permanent: true },
      { source: '/blog/satellites/duree-minimum-location-box', destination: '/blog/satellites/duree-minimum-location-box-montpellier', permanent: true },
      { source: '/blog/satellites/facteurs-prix-demenagement', destination: '/blog/satellites/facteurs-prix-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/plateformes-entraide-demenagement', destination: '/blog/satellites/plateformes-entraide-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-cle-en-main-prix', destination: '/blog/satellites/demenagement-cle-en-main-prix-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-piano-longue-distance', destination: '/blog/satellites/demenagement-piano-longue-distance-montpellier', permanent: true },
      { source: '/blog/satellites/prix-demenagement-maison-2025', destination: '/blog/satellites/prix-demenagement-maison-2025-montpellier', permanent: true },
      { source: '/blog/satellites/trouver-aide-derniere-minute-demenagement', destination: '/blog/satellites/trouver-aide-derniere-minute-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-piano-etages', destination: '/blog/satellites/demenagement-piano-etages-montpellier', permanent: true },
      { source: '/blog/satellites/delais-demenagement-international', destination: '/blog/satellites/delais-demenagement-international-montpellier', permanent: true },
      { source: '/blog/satellites/demenageur-pas-cher-fiable', destination: '/blog/satellites/demenageur-pas-cher-fiable-montpellier', permanent: true },
      { source: '/blog/satellites/tarif-demenagement-studio-2025', destination: '/blog/satellites/tarif-demenagement-studio-2025-montpellier', permanent: true },
      { source: '/blog/satellites/garde-meuble-par-quartier', destination: '/blog/satellites/garde-meuble-par-quartier-montpellier', permanent: true },
      { source: '/blog/satellites/prix-petit-demenagement', destination: '/blog/satellites/prix-petit-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/preparer-piano-pour-demenagement', destination: '/blog/satellites/preparer-piano-pour-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/prix-garde-meuble-2025', destination: '/blog/satellites/prix-garde-meuble-2025-montpellier', permanent: true },
      { source: '/blog/satellites/prix-demenagement-piano', destination: '/blog/satellites/prix-demenagement-piano-montpellier', permanent: true },
      { source: '/blog/satellites/piano-droit-vs-queue-demenagement', destination: '/blog/satellites/piano-droit-vs-queue-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/location-camion-avec-hayon', destination: '/blog/satellites/location-camion-avec-hayon-montpellier', permanent: true },
      { source: '/blog/satellites/combien-donner-aide-demenagement', destination: '/blog/satellites/combien-donner-aide-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/petit-demenagement-rapide', destination: '/blog/satellites/petit-demenagement-rapide-montpellier', permanent: true },
      { source: '/blog/satellites/quelle-taille-camion-louer-demenagement', destination: '/blog/satellites/quelle-taille-camion-louer-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-tpe-pme', destination: '/blog/satellites/demenagement-tpe-pme-montpellier', permanent: true },
      { source: '/blog/satellites/estimation-budget-demenagement-complet', destination: '/blog/satellites/estimation-budget-demenagement-complet-montpellier', permanent: true },
      { source: '/blog/satellites/petit-demenagement-diy', destination: '/blog/satellites/petit-demenagement-diy-montpellier', permanent: true },
      { source: '/blog/satellites/assurance-demenageur-couverture', destination: '/blog/satellites/assurance-demenageur-couverture-montpellier', permanent: true },
      { source: '/blog/satellites/devis-demenagement-comparer', destination: '/blog/satellites/devis-demenagement-comparer-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-europe', destination: '/blog/satellites/demenagement-europe-montpellier', permanent: true },
      { source: '/blog/satellites/checklist-demenagement-international', destination: '/blog/satellites/checklist-demenagement-international-montpellier', permanent: true },
      { source: '/blog/satellites/accorder-piano-apres-demenagement', destination: '/blog/satellites/accorder-piano-apres-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/location-camion-demenagement-pas-cher', destination: '/blog/satellites/location-camion-demenagement-pas-cher-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-bureaux-weekend', destination: '/blog/satellites/demenagement-bureaux-weekend-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-meuble-unique', destination: '/blog/satellites/demenagement-meuble-unique-montpellier', permanent: true },
      { source: '/blog/satellites/quelle-taille-box-garde-meuble', destination: '/blog/satellites/quelle-taille-box-garde-meuble-montpellier', permanent: true },
      { source: '/blog/satellites/aide-demenagement-personnes-agees', destination: '/blog/satellites/aide-demenagement-personnes-agees-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-serveurs-informatiques-entreprise', destination: '/blog/satellites/demenagement-serveurs-informatiques-entreprise-montpellier', permanent: true },
      { source: '/blog/satellites/europcar-location-demenagement', destination: '/blog/satellites/europcar-location-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-etudiant-petit-budget', destination: '/blog/satellites/demenagement-etudiant-petit-budget-montpellier', permanent: true },
      { source: '/blog/satellites/meilleur-demenageur-criteres', destination: '/blog/satellites/meilleur-demenageur-criteres-montpellier', permanent: true },
      { source: '/blog/satellites/formalites-douanieres-demenagement-international', destination: '/blog/satellites/formalites-douanieres-demenagement-international-montpellier', permanent: true },
      { source: '/blog/satellites/eviter-surcouts-demenagement', destination: '/blog/satellites/eviter-surcouts-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/etudiant-aide-demenagement-job', destination: '/blog/satellites/etudiant-aide-demenagement-job-montpellier', permanent: true },
      { source: '/blog/satellites/assurance-location-camion-demenagement', destination: '/blog/satellites/assurance-location-camion-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/prix-demenagement-longue-distance-paris', destination: '/blog/satellites/prix-demenagement-longue-distance-paris-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-groupe-prix', destination: '/blog/satellites/demenagement-groupe-prix-montpellier', permanent: true },
      { source: '/blog/satellites/prix-location-camion-20m3-2025', destination: '/blog/satellites/prix-location-camion-20m3-2025-montpellier', permanent: true },
      { source: '/blog/satellites/cartons-demenagement-gratuits', destination: '/blog/satellites/cartons-demenagement-gratuits-montpellier', permanent: true },
      { source: '/blog/satellites/assurance-demenagement-international', destination: '/blog/satellites/assurance-demenagement-international-montpellier', permanent: true },
      { source: '/blog/satellites/monte-meuble-demenagement-ecusson', destination: '/blog/satellites/monte-meuble-demenagement-ecusson-montpellier', permanent: true },
      { source: '/blog/satellites/caution-location-camion-demenagement', destination: '/blog/satellites/caution-location-camion-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/aide-ponctuelle-demenagement', destination: '/blog/satellites/aide-ponctuelle-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/demenageurs-specialises-piano', destination: '/blog/satellites/demenageurs-specialises-piano-montpellier', permanent: true },
      { source: '/blog/satellites/prix-demenagement-entreprise', destination: '/blog/satellites/prix-demenagement-entreprise-montpellier', permanent: true },
      { source: '/blog/satellites/self-stockage-vs-garde-meuble', destination: '/blog/satellites/self-stockage-vs-garde-meuble-montpellier', permanent: true },
      { source: '/blog/satellites/aides-financieres-demenagement', destination: '/blog/satellites/aides-financieres-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/demenageur-agree-assurance', destination: '/blog/satellites/demenageur-agree-assurance-montpellier', permanent: true },
      { source: '/blog/satellites/location-camionnette-petit-demenagement', destination: '/blog/satellites/location-camionnette-petit-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-solidaire', destination: '/blog/satellites/demenagement-solidaire-montpellier', permanent: true },
      { source: '/blog/satellites/prix-demenagement-t2-2025', destination: '/blog/satellites/prix-demenagement-t2-2025-montpellier', permanent: true },
      { source: '/blog/satellites/location-camion-demenagement-weekend', destination: '/blog/satellites/location-camion-demenagement-weekend-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-formule-economique', destination: '/blog/satellites/demenagement-formule-economique-montpellier', permanent: true },
      { source: '/blog/satellites/continuite-activite-pendant-demenagement-entreprise', destination: '/blog/satellites/continuite-activite-pendant-demenagement-entreprise-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-etudiant-solutions-economiques', destination: '/blog/satellites/demenagement-etudiant-solutions-economiques-montpellier', permanent: true },
      { source: '/blog/satellites/kilometrage-inclus-location-camion', destination: '/blog/satellites/kilometrage-inclus-location-camion-montpellier', permanent: true },
      { source: '/blog/satellites/prix-demenagement-international', destination: '/blog/satellites/prix-demenagement-international-montpellier', permanent: true },
      { source: '/blog/satellites/amenagement-nouveaux-locaux-entreprise', destination: '/blog/satellites/amenagement-nouveaux-locaux-entreprise-montpellier', permanent: true },
      { source: '/blog/satellites/normes-securite-demenagement-professionnel', destination: '/blog/satellites/normes-securite-demenagement-professionnel-montpellier', permanent: true },
      { source: '/blog/satellites/materiel-demenagement-piano', destination: '/blog/satellites/materiel-demenagement-piano-montpellier', permanent: true },
      { source: '/blog/satellites/box-temperature-controlee', destination: '/blog/satellites/box-temperature-controlee-montpellier', permanent: true },
      { source: '/blog/satellites/choisir-demenageur-international', destination: '/blog/satellites/choisir-demenageur-international-montpellier', permanent: true },
      { source: '/blog/satellites/location-camion-longue-duree-demenagement', destination: '/blog/satellites/location-camion-longue-duree-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/comparatif-prix-demenageurs-economiques', destination: '/blog/satellites/comparatif-prix-demenageurs-economiques-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-chambre-etudiante', destination: '/blog/satellites/demenagement-chambre-etudiante-montpellier', permanent: true },
      { source: '/blog/satellites/avis-demenageurs-google', destination: '/blog/satellites/avis-demenageurs-google-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-entrepot', destination: '/blog/satellites/demenagement-entrepot-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-studio', destination: '/blog/satellites/demenagement-studio-montpellier', permanent: true },
      { source: '/blog/satellites/contrat-demenagement-verifier-clauses', destination: '/blog/satellites/contrat-demenagement-verifier-clauses-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-archives-documents-entreprise', destination: '/blog/satellites/demenagement-archives-documents-entreprise-montpellier', permanent: true },
      { source: '/blog/satellites/prix-demenagement-par-m3', destination: '/blog/satellites/prix-demenagement-par-m3-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-maritime-aerien-comparatif', destination: '/blog/satellites/demenagement-maritime-aerien-comparatif-montpellier', permanent: true },
      { source: '/blog/satellites/preparer-aide-amis-demenagement', destination: '/blog/satellites/preparer-aide-amis-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/devis-gratuit-demenagement', destination: '/blog/satellites/devis-gratuit-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/stockage-pendant-demenagement', destination: '/blog/satellites/stockage-pendant-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/meilleure-periode-demenager-pas-cher', destination: '/blog/satellites/meilleure-periode-demenager-pas-cher-montpellier', permanent: true },
      { source: '/blog/satellites/surcout-demenagement-ecusson-aout', destination: '/blog/satellites/surcout-demenagement-ecusson-aout-montpellier', permanent: true },
      { source: '/blog/satellites/erreurs-eviter-demenagement-piano', destination: '/blog/satellites/erreurs-eviter-demenagement-piano-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-f1-t1', destination: '/blog/satellites/demenagement-f1-t1-montpellier', permanent: true },
      { source: '/blog/satellites/garde-meuble-etudiant-pas-cher', destination: '/blog/satellites/garde-meuble-etudiant-pas-cher-montpellier', permanent: true },
      { source: '/blog/satellites/acces-24-7-self-stockage', destination: '/blog/satellites/acces-24-7-self-stockage-montpellier', permanent: true },
      { source: '/blog/satellites/demenageur-weekend-disponibilite', destination: '/blog/satellites/demenageur-weekend-disponibilite-montpellier', permanent: true },
      { source: '/blog/satellites/louer-main-oeuvre-demenagement', destination: '/blog/satellites/louer-main-oeuvre-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/planning-demenagement-entreprise-preparation', destination: '/blog/satellites/planning-demenagement-entreprise-preparation-montpellier', permanent: true },
      { source: '/blog/satellites/demenagement-etudiant-pas-cher', destination: '/blog/satellites/demenagement-etudiant-pas-cher-montpellier', permanent: true },
      { source: '/blog/satellites/responsabilite-aide-non-professionnelle-demenagement', destination: '/blog/satellites/responsabilite-aide-non-professionnelle-demenagement-montpellier', permanent: true },
      { source: '/blog/satellites/assurance-garde-meuble-obligatoire', destination: '/blog/satellites/assurance-garde-meuble-obligatoire-montpellier', permanent: true },

      // MAUVAIS DOSSIERS (articles dans piliers au lieu de satellites)
      { source: '/blog/demenagement-entreprise-montpellier/satellites/prix-demenagement-entreprise-montpellier', destination: '/blog/satellites/prix-demenagement-entreprise-montpellier', permanent: true },
      { source: '/blog/location-camion-demenagement-montpellier/satellites/assurance-location-utilitaire-montpellier', destination: '/blog/satellites/assurance-location-utilitaire-montpellier', permanent: true },

      // PILIERS : Mauvais noms → corrects
      { source: '/blog/location-camion-demenagement/location-camion-demenagement', destination: '/blog/location-camion-demenagement-montpellier/location-camion-demenagement-montpellier-guide', permanent: true },
      { source: '/blog/demenageur/demenageur', destination: '/blog/demenageur-montpellier/demenageur-montpellier-guide', permanent: true },
      { source: '/blog/demenagement-piano/demenagement-piano', destination: '/blog/demenagement-piano-montpellier/demenagement-piano-montpellier-guide', permanent: true },
      { source: '/blog/petit-demenagement/petit-demenagement', destination: '/blog/petit-demenagement-montpellier/petit-demenagement-montpellier-guide', permanent: true },
      { source: '/blog/demenagement-pas-cher/demenagement-pas-cher', destination: '/blog/demenagement-pas-cher-montpellier/demenagement-pas-cher-montpellier-guide', permanent: true },
      { source: '/blog/aide-demenagement-particulier/aide-demenagement-particulier', destination: '/blog/aide-demenagement-particulier-montpellier/aide-demenagement-particulier-montpellier-guide', permanent: true },
      { source: '/blog/prix-demenagement/prix-demenagement', destination: '/blog/prix-demenagement-montpellier/prix-demenagement-montpellier-guide', permanent: true },
      { source: '/blog/demenagement-entreprise/demenagement-entreprise', destination: '/blog/demenagement-entreprise-montpellier/demenagement-entreprise-montpellier-guide', permanent: true },
      { source: '/blog/demenagement-international/demenagement-international', destination: '/blog/demenagement-international-montpellier/demenagement-international-montpellier-guide', permanent: true },
      { source: '/blog/garde-meuble/garde-meuble-guide-complet', destination: '/blog/garde-meuble-montpellier/garde-meuble-montpellier-guide-complet', permanent: true },
      { source: '/blog/demenagement-international/demenagement-international-guide', destination: '/blog/demenagement-international-montpellier/demenagement-international-montpellier-guide', permanent: true },
      { source: '/blog/aide-demenagement/aide-demenagement-guide', destination: '/blog/aide-demenagement-particulier-montpellier/aide-demenagement-particulier-montpellier-guide', permanent: true },
      { source: '/blog/petit-demenagement/petit-demenagement-guide', destination: '/blog/petit-demenagement-montpellier/petit-demenagement-montpellier-guide', permanent: true },
      { source: '/blog/demenagement-pas-cher/demenagement-pas-cher-guide', destination: '/blog/demenagement-pas-cher-montpellier/demenagement-pas-cher-montpellier-guide', permanent: true },
      { source: '/blog/demenagement-entreprise/demenagement-entreprise-guide', destination: '/blog/demenagement-entreprise-montpellier/demenagement-entreprise-montpellier-guide', permanent: true },
      { source: '/blog/demenagement-piano/demenagement-piano-guide', destination: '/blog/demenagement-piano-montpellier/demenagement-piano-montpellier-guide', permanent: true },
      { source: '/blog/demenageur/demenageur-guide-complet', destination: '/blog/demenageur-montpellier/demenageur-montpellier-guide', permanent: true },
      { source: '/blog/prix-demenagement/prix-demenagement-guide', destination: '/blog/prix-demenagement-montpellier/prix-demenagement-montpellier-guide', permanent: true },
      { source: '/blog/location-camion-demenagement/location-camion-demenagement-guide', destination: '/blog/location-camion-demenagement-montpellier/location-camion-demenagement-montpellier-guide', permanent: true },

      // CATÉGORIES VIDES → /blog
      { source: '/blog/piano', destination: '/blog', permanent: true },
      { source: '/blog/international', destination: '/blog', permanent: true },
      { source: '/blog/longue-distance', destination: '/blog', permanent: true },
      { source: '/blog/prix', destination: '/blog', permanent: true },
      { source: '/blog/urgent', destination: '/blog', permanent: true },
      { source: '/blog/entreprise', destination: '/blog', permanent: true },
      { source: '/blog/devis', destination: '/blog', permanent: true },
      { source: '/blog/pas-cher', destination: '/blog', permanent: true },
      { source: '/blog/garde-meuble', destination: '/blog', permanent: true },
      { source: '/blog/etudiant', destination: '/blog', permanent: true },

      { source: '/montpellier-vers-montpellier', destination: '/', permanent: true },
      { source: '/montpellier-vers-nantes', destination: '/montpellier-vers-nantes', permanent: true },
      { source: '/montpellier-vers-espagne', destination: '/montpellier-vers-espagne', permanent: true },
      { source: '/quartiers-montpellier', destination: '/quartiers-montpellier', permanent: true },

      // SERVICES : Majuscules + minuscules dupliquées
      { source: '/services/demenagement-standard-Montpellier', destination: '/services/demenagement-standard-montpellier', permanent: true },
      { source: '/services/demenagement-economique-Montpellier', destination: '/services/demenagement-economique-montpellier', permanent: true },
      { source: '/services/demenagement-premium-Montpellier', destination: '/services/demenagement-premium-montpellier', permanent: true },
      { source: '/services/demenagement-economique-montpellier', destination: '/services/demenagement-economique-montpellier', permanent: true },
      { source: '/services/demenagement-standard-montpellier', destination: '/services/demenagement-standard-montpellier', permanent: true },
      { source: '/services/demenagement-premium-montpellier', destination: '/services/demenagement-premium-montpellier', permanent: true },

      // PAGES LÉGALES : Trailing slash
      { source: '/mentions-legales/', destination: '/mentions-legales', permanent: true },
      { source: '/cgv/', destination: '/cgv', permanent: true },
      { source: '/politique-confidentialite/', destination: '/politique-confidentialite', permanent: true },

      // ANCIENNES URLs
      { source: '/estimation-demenagement-montpellier/', destination: '/estimation-rapide', permanent: true },
      { source: '/prix-demenagement-montpellier/', destination: '/blog/prix-demenagement-montpellier/prix-demenagement-montpellier-guide', permanent: true },
      { source: '/devis-demenagement-montpellier/', destination: '/estimation-rapide', permanent: true },
    ];
  }
};

export default nextConfig;

